# Generated by Django 5.2 on 2025-05-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_usertransactions_month_usertransactions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
